# Generated by Django 3.2 on 2021-05-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oinkerprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oinkerprofile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='oinkerprofile.OinkerProfile'),
        ),
    ]
