# Generated by Django 3.2 on 2021-05-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oinkerprofile', '0002_alter_oinkerprofile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='oinkerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar-2.jpg', null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='oinkerprofile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='oinkerprofile.OinkerProfile'),
        ),
    ]
